name: tasty_link
description: "A Flutter app for extracting and managing recipes from links"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management & Routing
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  
  # UI & Fonts
  google_fonts: ^6.1.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  
  # Storage & Offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Media & Permissions
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  
  # Monetization & Device
  in_app_purchase: ^3.1.11
  package_info_plus: ^4.2.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8
  firebase_messaging: ^14.7.10
  
  # OCR
  flutter_tesseract_ocr: ^0.4.14
  
  # Language Detection & Translation
  google_mlkit_language_id: ^0.10.0
  google_mlkit_translation: ^0.9.0
  
  # Crypto
  crypto: ^3.0.3
  
  # Connectivity
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/brand/
    - assets/illustrations/
    - assets/tessdata/
