// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-VhVKjKnpbUqC7LeS1U04Wjx_7QXQ8uU',
    appId: '1:58215004641:android:9b4a0acb8c0ca68763faa0',
    messagingSenderId: '58215004641',
    projectId: 'tastylink-bd947',
    storageBucket: 'tastylink-bd947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1bjtA2hNjkm7tEV5IF8Cst7fYk36vaw',
    appId: '1:58215004641:ios:edd92820a3188bbb63faa0',
    messagingSenderId: '58215004641',
    projectId: 'tastylink-bd947',
    storageBucket: 'tastylink-bd947.firebasestorage.app',
    iosBundleId: 'com.blueprint.tastylink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLcMdBXs_1KI92uUJcxyBVLiIvOa3mT9c',
    appId: '1:58215004641:web:9dc00361212442b063faa0',
    messagingSenderId: '58215004641',
    projectId: 'tastylink-bd947',
    authDomain: 'tastylink-bd947.firebaseapp.com',
    storageBucket: 'tastylink-bd947.firebasestorage.app',
    measurementId: 'G-B1GQQCB2RV',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLcMdBXs_1KI92uUJcxyBVLiIvOa3mT9c',
    appId: '1:58215004641:web:9dc00361212442b063faa0',
    messagingSenderId: '58215004641',
    projectId: 'tastylink-bd947',
    authDomain: 'tastylink-bd947.firebaseapp.com',
    storageBucket: 'tastylink-bd947.firebasestorage.app',
    measurementId: 'G-B1GQQCB2RV',
  );

}